# The URL the site will be built for
base_url = "https://mkaz.blog/"
title = "mkaz.blog"

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "agola-dark"

[extra]
# Custom Variables
author = "Marcus Kazmierczak"
